language: node_js
version: 1.0
node_js:
 - "8"
install:
 - npm install codecov -g
 - npm install
before_script: 
 - npm run build
 - npm run buildPure
script:
 - npm run test
after_success:
 - codecov
 - test $TRAVIS_BRANCH = "master" && npm pack 
stage:
 - build
 - release
jobs:
 include:
  - stage: build
    if: branch != master
  - stage: release
    if: branch = master      
deploy:
  edge: true
  provider: npm
  api_key: "$NPM_API_KEY"
  email: "$NPM_EMAIL"
  skip_cleanup: true
  on:
    tags: true
    branch: master
 
notifications:
  email:
    on_success: never
    on_failure: never
